import { GalleryItem } from "./types";

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-1",
    src: "/gallery/24PP05674.JPG",
    alt: "GUSTO Inauguration Ceremony",
    caption: "Dignitaries and faculty inaugurating the National Level Symposium at GCEE",
    category: "ceremony",
  },
  {
    id: "gal-2",
    src: "/gallery/24PP05682.JPG",
    alt: "Auditorium Address",
    caption: "Keynote address to participants from across various engineering colleges",
    category: "ceremony",
  },
  {
    id: "gal-3",
    src: "/gallery/24PP05685.JPG",
    alt: "Lighting the Kuthuvilakku",
    caption: "Auspicious commencement of the symposium proceedings",
    category: "ceremony",
  },
  {
    id: "gal-4",
    src: "/gallery/24PP05692.JPG",
    alt: "Faculty & Organizers Felicitation",
    caption: "Department of Information Technology leadership and faculty advisors",
    category: "ceremony",
  },
  {
    id: "gal-5",
    src: "/gallery/24PP05703.JPG",
    alt: "Participants Audience",
    caption: "Student delegates engaged during the morning symposium briefing",
    category: "symposium",
  },
  {
    id: "gal-6",
    src: "/gallery/24PP05709.JPG",
    alt: "Auditorium Assembly",
    caption: "Grand gathering of engineering students in the GCEE Seminar Hall",
    category: "symposium",
  },
  {
    id: "gal-7",
    src: "/gallery/24PP05739.JPG",
    alt: "Paper Presentation Session",
    caption: "Student researchers defending their technical abstracts before the review jury",
    category: "events",
  },
  {
    id: "gal-8",
    src: "/gallery/24PP05746.JPG",
    alt: "Technical Evaluation",
    caption: "Jury assessment of participants presenting innovative software solutions",
    category: "events",
  },
  {
    id: "gal-9",
    src: "/gallery/24PP05752.JPG",
    alt: "Project Presentation Live Demo",
    caption: "Hardware and software project exhibition in the IT Computer Lab",
    category: "events",
  },
  {
    id: "gal-10",
    src: "/gallery/24PP05759.JPG",
    alt: "Coding Trial Participants",
    caption: "Students competing in intense algorithmic debugging and blind coding rounds",
    category: "events",
  },
  {
    id: "gal-11",
    src: "/gallery/24PP05789.JPG",
    alt: "Interactive Games & Non-Tech Event",
    caption: "Engaging crowd challenges and technical connections session",
    category: "events",
  },
  {
    id: "gal-12",
    src: "/gallery/24PP05806.JPG",
    alt: "Auditorium Reaction",
    caption: "High-energy moments during symposium multimedia reveals",
    category: "symposium",
  },
  {
    id: "gal-13",
    src: "/gallery/24PP05819.JPG",
    alt: "Valedictory Prize Distribution",
    caption: "Recognizing outstanding technical presentations and coding champions",
    category: "ceremony",
  },
  {
    id: "gal-14",
    src: "/gallery/24PP05841.JPG",
    alt: "Winners with Certificates",
    caption: "Celebrating student excellence with trophies and cash awards",
    category: "ceremony",
  },
  {
    id: "gal-15",
    src: "/gallery/24PP05900.JPG",
    alt: "GUSTO Organizing Committee",
    caption: "AIT student coordinators and volunteers making GUSTO a grand success",
    category: "campus",
  },
  {
    id: "gal-16",
    src: "/gallery/24PP05988.JPG",
    alt: "Campus Memories",
    caption: "Participants networking across the Department of Information Technology lawns",
    category: "campus",
  },
  {
    id: "gal-17",
    src: "/gallery/24PP06016.JPG",
    alt: "GUSTO Stage Celebration",
    caption: "Closing ceremonies and triumphant moments of the symposium",
    category: "ceremony",
  },
  {
    id: "gal-18",
    src: "/gallery/GOW06781.JPG",
    alt: "Event Action Shot",
    caption: "Participants engaged during the fast-paced competitive rounds",
    category: "events",
  },
  {
    id: "gal-19",
    src: "/gallery/GOW06820.JPG",
    alt: "Symposium Finale",
    caption: "Students gathering for the concluding symposium group picture",
    category: "campus",
  },
];
